docker:
    repo_url: swr.cn-north-4.myhuaweicloud.com/openeuler-embedded/openeuler-container
    tag_map:
        openEuler-23.03: latest
        master: latest
        openEuler-22.03-LTS-SP2: 22.03-lts-sp2
basic_repo:
    yocto_meta_openeuler: 
        path: yocto-meta-openeuler
        remote_url: https://gitee.com/openeuler/yocto-meta-openeuler.git
        branch: master